### ISSUE TITLE
The POST method is not supported for this route. Supported methods: GET, HEAD.

### ISSUE THREAD

**Issue by 0x13ens** [LaravelDaily/Laravel-Login-Register-Modal-Bootstrap#1]
As title? when using the register route.

**Comment by PovilasKorop** [comment]
Sorry can you specify exactly the code you wrote, or how you called register route? We don't get this error on our side.

**Comment by phatx88** [comment]
Hi there, I have the same problem too. I was wonder if it is resolved yet?  Is it because the route name is pointing to the GET Method instead?
![image](https://user-images.githubusercontent.com/66936482/114420774-d1cf4980-9bde-11eb-98d3-bc825150bd6b.png)

**Comment by PovilasKorop** [comment]
@phatx88 there's a route GET register, and separate POST register.

From Laravel UI package - the form has a POST request to register, exactly as we're doing here:
```
<form method="POST" action="{{ route('register') }}">
```

Source: https://github.com/laravel/ui/blob/3.x/src/Auth/bootstrap-stubs/auth/register.stub

So not sure what/why is not working for you.

**Comment by phatx88** [comment]
Hi,
I finally get the ajax working but there is a problem, it seems after
sending the data to server I only get the error response. Here is the
screenshot.

[image: image.png]

  The headers : { application/json } attribute doesn't seem to work so i
have to change it thus. Everything else is just copying and pasting exactly
from the source code.

[image: image.png]

this is what i get. The email already exist in database everything else
should be valid except the email only. So the error should only show on the
email field.

[image: image.png]

I apologized for changing your code slightly. My guessing that the problem
is within the headers { application/json } attribute, I will continue to
work on this until I find a solution.

Thank you very much,

**Comment by PovilasKorop** [comment]
@phatx88 your images don't show up, so I can't give advice, but generally, it seems not the issue with our project and our code, but rather with the way how you use it. In my demo for this project, all worked fine.

So, closing the issue for now.
